// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_KZEvCHWgzw67fPKX8xiuA_y1Y4qtwdU',
    appId: '1:647099793032:web:427c3045411d2ab871a93d',
    messagingSenderId: '647099793032',
    projectId: 'grid-cda8b',
    authDomain: 'grid-cda8b.firebaseapp.com',
    storageBucket: 'grid-cda8b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjZVAGIhGlVR5gZZx4LAzAeVwA-Gb9mC8',
    appId: '1:647099793032:android:a6491088c5276b4571a93d',
    messagingSenderId: '647099793032',
    projectId: 'grid-cda8b',
    storageBucket: 'grid-cda8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKuAvSNL_-qA2PL-5XHKh2jr6HrnJOctM',
    appId: '1:647099793032:ios:c6b1ef861889c94171a93d',
    messagingSenderId: '647099793032',
    projectId: 'grid-cda8b',
    storageBucket: 'grid-cda8b.appspot.com',
    iosBundleId: 'com.example.grid',
  );
}
